# Generated by Django 3.0.5 on 2020-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, verbose_name='email address'),
        ),
    ]
